name: Run tests and deploy web version

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deployment:
    strategy:
      fail-fast: false
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
        ocaml-compiler:
          - 5.3.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: 'true'
          fetch-depth: 0
          filter: tree:0

      # OCaml build and tests
      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-pin: false
      - name: Install OCaml dependencies
        run: |
          make deps
      - name: Run tests
        run: |
          make test

      # Generate documentation
      - name: Install odoc
        run: |
          opam install odoc
      - name: Generate documentation
        run: |
          make doc

      # Build web version
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Node.js dependencies
        run: |
          make web-deps
      - name: Build web version
        run: |
          make js

      # Upload artifact
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
